#!/usr/bin/python3

CC := gcc
NAME := school
RM := rm -f

SRC := main.c school.c

OBJ := $(SRC:.c=.o)

CFLAGS := -Wall -Werror -Wextra -pedantic

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

%.o: %.c
	$(CC) -c $< -o $@

clean:
	$(RM) $(wildcard *~) $(wildcard *#) $(wildcard *.swp) $(wildcard *.o)

oclean:
	$(RM) $(OBJ)

fclean: clean oclean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean oclean fclean re

